/**
 * Docusaurus v3.
 *
 * Pages are readable: the docs tree, each page's frontmatter, and `_category_.json` are all plain
 * data, and Docusaurus derives a doc's id and route from its path by the same arithmetic.
 *
 * Navigation is readable only in one of its two modes. A site with no `sidebars.*` file gets the
 * autogenerated sidebar, which is exactly the filesystem plus `_category_.*` plus `sidebar_position`
 * — a statement by the source, and safe to read. A site WITH a `sidebars.js`/`.ts` states its
 * navigation in a Node module that may scan directories, import generated JSON or call a function
 * to build itself. That cannot be read without executing it, and executing a customer's build
 * script to migrate them is not something this tool does. Such a site therefore reports no
 * navigation witness, and `source-navigation-proven` refuses to certify its sidebar in exact mode
 * rather than shipping a guess — the operator supplies a reviewed tree instead.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { basename, join, relative, resolve } from 'node:path';
import { pageIdFromPlatform } from '../session/ids.js';
import { firstHeading, statedFrontmatter, titleFromFilename } from './frontmatter.js';
import type { SourceNavigationNode, Tree, TreePage } from '../nav/tree.js';

export const DOCUSAURUS_CONFIGS = ['docusaurus.config.js', 'docusaurus.config.ts', 'docusaurus.config.mjs', 'docusaurus.config.cjs'];
const SIDEBAR_FILES = ['sidebars.js', 'sidebars.ts', 'sidebars.mjs', 'sidebars.cjs', 'sidebars.json'];

export interface DocusaurusRepo {
  root: string;
  docsRoot: string;
  /** Released versions, newest first, as versions.json states them. */
  versions?: string[];
  /** Translated locales under i18n/; the default locale is stated in the config and is not read. */
  locales?: string[];
  tree: Tree;
  /** Pages the source marks `draft` or `unlisted`; Docusaurus does not publish a draft. */
  hidden: string[];
  /** The sidebars module, when the site has one: its navigation cannot be read without running it. */
  sidebarsFile?: string;
}

interface Category { label?: string; position?: number }

function categoryOf(dir: string): Category {
  for (const name of ['_category_.json', '_category_.yml', '_category_.yaml']) {
    const path = join(dir, name);
    if (!existsSync(path)) continue;
    const body = readFileSync(path, 'utf8');
    if (name.endsWith('.json')) { try { return JSON.parse(body) as Category; } catch { return {}; } }
    // the two keys this adapter uses are scalars in both forms
    const label = /^label:[ \t]*(.+)$/m.exec(body)?.[1]?.trim().replace(/^(["'])([\s\S]*)\1$/, '$2');
    const position = Number(/^position:[ \t]*(.+)$/m.exec(body)?.[1]?.trim());
    return { ...(label ? { label } : {}), ...(Number.isFinite(position) ? { position } : {}) };
  }
  return {};
}

/** Docusaurus orders by `sidebar_position`, then by a numeric filename prefix, then by filename. */
const positionOf = (stated: Record<string, string>, name: string): number => {
  const declared = Number(stated.sidebar_position);
  if (Number.isFinite(declared)) return declared;
  const prefix = Number(/^(\d+)[-_.]/.exec(name)?.[1]);
  return Number.isFinite(prefix) ? prefix : Number.MAX_SAFE_INTEGER;
};

export function readDocusaurusRepo(rootIn: string): DocusaurusRepo {
  const root = resolve(rootIn);
  const docsRoot = existsSync(join(root, 'docs')) ? join(root, 'docs') : root;
  const sidebarsFile = SIDEBAR_FILES.map((name) => join(root, name)).find(existsSync);
  const pages: TreePage[] = [];
  const hidden: string[] = [];
  let order = 0;

  const walk = (dir: string, group: string[]): SourceNavigationNode[] => {
    const entries = readdirSync(dir, { withFileTypes: true }).filter((entry) => !entry.isSymbolicLink());
    const files = entries.filter((entry) => entry.isFile() && /\.mdx?$/i.test(entry.name));
    const directories = entries.filter((entry) => entry.isDirectory() && !entry.name.startsWith('.') && entry.name !== 'node_modules');

    const items: Array<{ position: number; name: string; node: SourceNavigationNode }> = [];
    for (const file of files) {
      const path = join(dir, file.name);
      const body = readFileSync(path, 'utf8');
      const stated = statedFrontmatter(body);
      const source = relative(root, path);
      if (stated.draft === 'true' || stated.unlisted === 'true') { hidden.push(source); continue; }
      // The frozen file is the identity, which is what the independent source enumeration counts.
      // A Docusaurus doc id is a routing name, and using it here would make the two disagree about
      // which pages exist.
      const id = pageIdFromPlatform('docusaurus', source);
      const title = stated.title ?? firstHeading(body) ?? titleFromFilename(file.name);
      const route = stated.slug?.startsWith('/')
        ? stated.slug
        : `/${[...group, (stated.slug ?? basename(file.name).replace(/\.mdx?$/i, '').replace(/^\d+[-_.]/, '')).replace(/^\/+/, '')].join('/')}`;
      pages.push({
        id,
        title,
        ...(stated.sidebar_label ? { sidebarTitle: stated.sidebar_label } : {}),
        ...(stated.description ? { description: stated.description } : {}),
        source,
        group: [...group],
        order: order++,
        oldPath: route.replace(/\/index$/i, '/'),
        migrate: true,
        reason: 'docs tree',
      });
      items.push({ position: positionOf(stated, file.name), name: file.name, node: { type: 'page', pageId: id, title: stated.sidebar_label ?? title } });
    }

    for (const directory of directories) {
      const path = join(directory.parentPath ?? dir, directory.name);
      const category = categoryOf(path);
      const label = category.label ?? titleFromFilename(directory.name);
      const children = walk(path, [...group, directory.name]);
      if (children.length) items.push({ position: category.position ?? Number.MAX_SAFE_INTEGER, name: directory.name, node: { type: 'group', label, children } });
    }

    return items.sort((a, b) => a.position - b.position || a.name.localeCompare(b.name)).map((item) => item.node);
  };

  const navigation = walk(docsRoot, []);
  const currentPages = pages.length;

  // A versioned site keeps each released version beside the current one, newest first in
  // versions.json, and Docusaurus serves that newest one at the base path.
  const versionsFile = join(root, 'versions.json');
  let versions: string[] = [];
  if (existsSync(versionsFile)) {
    try { versions = (JSON.parse(readFileSync(versionsFile, 'utf8')) as string[]).filter((version) => typeof version === 'string'); }
    catch { versions = []; }
  }
  if (versions.length) {
    // Docusaurus normally serves the newest released version at the base path and current work
    // under /next. A JS config may override that routing, so the tree is deliberately left without
    // a certified navigation source below; the routes remain unique and reviewable instead of five
    // copies of /intro silently colliding.
    for (const page of pages.slice(0, currentPages)) {
      page.version = 'current';
      page.oldPath = `/${['next', (page.oldPath ?? '').replace(/^\/+/, '')].filter(Boolean).join('/')}`.replace(/\/$/, '/');
    }
  }
  for (const version of versions) {
    const versionRoot = join(root, 'versioned_docs', `version-${version}`);
    if (!existsSync(versionRoot)) continue;
    const before = pages.length;
    walk(versionRoot, []);
    for (const page of pages.slice(before)) {
      page.version = version;
      if (version !== versions[0]) page.oldPath = `/${version}/${(page.oldPath ?? '').replace(/^\/+/, '')}`;
    }
  }

  // A translated site keeps each locale's pages under i18n/<locale>/, and the default locale stays
  // in docs/. Which locale is the default is stated in the config, which is code, so the pages left
  // in docs/ are recorded without one rather than being labelled with a guess.
  const localeRoot = join(root, 'i18n');
  const locales: string[] = existsSync(localeRoot)
    ? readdirSync(localeRoot, { withFileTypes: true }).filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort()
    : [];
  const configPath = DOCUSAURUS_CONFIGS.map((name) => join(root, name)).find(existsSync);
  const configBody = configPath ? readFileSync(configPath, 'utf8') : '';
  const defaultLocale = /\bdefaultLocale\s*:\s*(['"])([^'"]+)\1/.exec(configBody)?.[2] ?? 'en';
  if (locales.length) for (const page of pages) page.locale = defaultLocale;
  for (const locale of locales) {
    const base = join(localeRoot, locale, 'docusaurus-plugin-content-docs');
    if (!existsSync(base)) continue;
    for (const entry of readdirSync(base, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const version = entry.name === 'current' ? (versions.length ? 'current' : undefined) : entry.name.replace(/^version-/, '');
      const before = pages.length;
      walk(join(base, entry.name), []);
      for (const page of pages.slice(before)) {
        page.locale = locale;
        if (version) page.version = version;
        const versionPrefix = version === 'current' ? 'next' : version && version !== versions[0] ? version : '';
        page.oldPath = `/${[locale, versionPrefix, (page.oldPath ?? '').replace(/^\/+/, '')].filter(Boolean).join('/')}`;
      }
    }
  }

  const dimensionsNeedConfig = versions.length > 0 || locales.length > 0;

  return {
    root,
    docsRoot,
    ...(versions.length ? { versions } : {}),
    ...(locales.length ? { locales } : {}),
    // A site with a sidebars module states its navigation there, in code this tool will not run.
    tree: {
      scope: 'full',
      platform: 'docusaurus',
      pages,
      // A site with a sidebars module states its navigation there, in code this tool will not run.
      // JS configuration decides version aliases, default locale and sidebar sets. Until that code
      // can be read without executing it, do not certify a derived multidimensional sidebar as the
      // source's statement. buildNavigation still derives a complete reviewable tree from pages.
      ...(sidebarsFile || dimensionsNeedConfig ? {} : { navigation, navigationSource: 'source-config' as const }),
      ...(versions.length ? { defaultVersion: versions[0] } : {}),
      ...(locales.length ? { defaultLocale } : {}),
    },
    hidden,
    ...(sidebarsFile ? { sidebarsFile: relative(root, sidebarsFile) } : {}),
  };
}
